### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by rodromartin** [rodromartin/tpuno#2]
Nos quedan un par de cosas por hacer:  

- [ ] Preguntar en la lista de mails si esta bien el tipo de dato Amigo (explicar el use case de si dos Clientes son amigos entre si)
- [ ] Leer el enunciado de la parte 2. Dividirnos los temas
- [ ] Comentar el código con la resolucion del punto 1.
